# Generated by Django 5.0.2 on 2025-04-21 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('platform', models.CharField(choices=[('Microsoft Windows', 'Microsoft Windows'), ('Sony PlayStation 5', 'Sony PlayStation 5'), ('Sony PlayStation 4', 'Sony PlayStation 4'), ('Sony PlayStation 3', 'Sony PlayStation 3'), ('Sony PlayStation 2', 'Sony PlayStation 2'), ('Sony PlayStation', 'Sony PlayStation'), ('Microsoft Xbox Series X/S', 'Microsoft Xbox Series X/S'), ('Microsoft Xbox One', 'Microsoft Xbox One'), ('Nintendo Switch', 'Nintendo Switch'), ('Nintendo Wii U', 'Nintendo Wii U'), ('Nintendo Wii', 'Nintendo Wii'), ('Nintendo GameCube', 'Nintendo GameCube'), ('Nintendo Game Boy Advance', 'Nintendo Game Boy Advance'), ('Nintendo Game Boy Color', 'Nintendo Game Boy Color'), ('Nintendo Game Boy', 'Nintendo Game Boy'), ('Nintendo DS', 'Nintendo DS'), ('Nintendo 3DS', 'Nintendo 3DS'), ('Nintendo Switch', 'Nintendo Switch'), ('Nintendo Wii U', 'Nintendo Wii U'), ('Nintendo 64', 'Nintendo 64'), ('Nintendo NES', 'Nintendo NES'), ('Nintendo SNES', 'Nintendo SNES'), ('Other', 'Other')], max_length=100, verbose_name='Platform')),
                ('publisher', models.CharField(max_length=100, verbose_name='Publisher')),
                ('release_year', models.IntegerField(blank=True, null=True, verbose_name='Release Year')),
                ('number_of_players', models.PositiveIntegerField(default=1, help_text='Minimum number of players required', verbose_name='Number of Players')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], null=True, verbose_name='Rating')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.genre', verbose_name='Genre')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['title'],
            },
        ),
    ]
