# Generated by Django 5.0.2 on 2025-04-21 14:11

import games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_game_completed_remove_game_publisher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=games.models.game_image_path, verbose_name='Game Image'),
        ),
    ]
