# Generated by Django 5.0.2 on 2025-04-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, help_text='A brief description of the game', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='game',
            name='lan_playable',
            field=models.BooleanField(default=False, help_text='Whether the game supports LAN multiplayer', verbose_name='LAN Playable'),
        ),
    ]
