# Generated by Django 5.0.2 on 2025-04-22 17:50

import games.fields
import games.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_userapikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=games.fields.CompressedImageField(blank=True, null=True, upload_to=games.models.game_image_path, verbose_name='Game Image'),
        ),
        migrations.DeleteModel(
            name='UserAPIKey',
        ),
    ]
