# Generated by Django 5.0.2 on 2025-04-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_game_image_delete_userapikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(choices=[('Microsoft Windows', 'Microsoft Windows'), ('Linux', 'Linux'), ('Mac', 'Mac'), ('Sony PlayStation 5', 'Sony PlayStation 5'), ('Sony PlayStation 4', 'Sony PlayStation 4'), ('Sony PlayStation 3', 'Sony PlayStation 3'), ('Sony PlayStation 2', 'Sony PlayStation 2'), ('Sony PlayStation', 'Sony PlayStation'), ('Microsoft Xbox Series X/S', 'Microsoft Xbox Series X/S'), ('Microsoft Xbox One', 'Microsoft Xbox One'), ('Nintendo Switch', 'Nintendo Switch'), ('Nintendo Wii U', 'Nintendo Wii U'), ('Nintendo Wii', 'Nintendo Wii'), ('Nintendo GameCube', 'Nintendo GameCube'), ('Nintendo Game Boy Advance', 'Nintendo Game Boy Advance'), ('Nintendo Game Boy Color', 'Nintendo Game Boy Color'), ('Nintendo Game Boy', 'Nintendo Game Boy'), ('Nintendo DS', 'Nintendo DS'), ('Nintendo 3DS', 'Nintendo 3DS'), ('Nintendo Switch', 'Nintendo Switch'), ('Nintendo Wii U', 'Nintendo Wii U'), ('Nintendo 64', 'Nintendo 64'), ('Nintendo NES', 'Nintendo NES'), ('Nintendo SNES', 'Nintendo SNES'), ('Other', 'Other')], max_length=100, verbose_name='Platform'),
        ),
    ]
